
"""
Revision ID: 1462c3027f99
Revises: 20240320_initial
Create Date: 2025-05-30 15:12:17.782684+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1462c3027f99'
down_revision = '20240320_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('data_files_project_id_fkey', 'data_files', type_='foreignkey')
    op.drop_column('data_files', 'project_id')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_files', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('data_files_project_id_fkey', 'data_files', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ### 